### ISSUE TITLE
issues #1

### ISSUE THREAD

**Issue by giulianaerro** [havikhavik/apx-desafio-m4#1]
![Captura de pantalla de 2021-10-13 20-19-29](https://user-images.githubusercontent.com/73187805/137226153-67596c33-459c-46fe-9fdb-6cf98ea4fa67.png)

Hola lucas! anda todo genial, el unico detalle es el de la captura, que si entrarías desde una tablet se vería así. Podes arreglarlo por ejemplo usando display flex en lugar de grid, y un flex-direction: row. El resto funciona todo bien. Éxitos en el próximo modulo 👍🏼

**Comment by havikhavik** [comment]
Hola Giuliana, gracias por mirar y probar mi Portfolio! En principio te comento que utilicé la propiedad Grid para disponer de cada ítem (los trabajos y los servicios realizados) en una grilla cuando estos utilizan todo el ancho disponible en pantalla. 
Por un lado me da la posibilidad de seguir cargando recursos a través de Contentful sin tener que ir modificando el layout manualmente cada vez que esto pase y por otro lado me pareció mucho mas agradable a nivel visual.

En cuanto al problema que mencionaste, ocurría porque el ultimo elemento rompía el ancho en pantalla, lo pude solucionar implementando la propiedad grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));  Lo que hace esta propiedad es definir de forma automática la cantidad de columnas dependiendo el tamaño de la pantalla. 

Te agradezco de nuevo por chequear el trabajo y subo capturas con el diseño funcionando correctamente!

![fixed](https://user-images.githubusercontent.com/74418375/137241537-fe452a91-4ff9-4f16-b579-961d93eb4345.jpg)
![fixed3](https://user-images.githubusercontent.com/74418375/137241534-b559c5d3-6154-4064-9dae-40b5cb12f880.jpg)
![fixed2](https://user-images.githubusercontent.com/74418375/137241540-a965d9f3-d392-495f-9ec3-68460eb8feec.jpg)
