### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by MatiToledo** [havikhavik/apx-desafio-m4#2]
Hola Lucas !! Estuve viendo la page y esta excelente, todo increíble, solo note 2 cositas que habría que arreglar para terminar de pulir la page

1. En mobile, en la "hero-section" la imagen se duplica en vez de verse entera, habria que ponerle algo para que la imagen se expanda a todo el contenedor, podría ser algo como un background-size: cover;
2. Hay un problema tanto en portfolio como en servicios que en cierto momento la page crashea, habria que ver de solucionar eso con las media queries
![l1](https://user-images.githubusercontent.com/82173133/137228071-0ebdc62c-f7ca-42af-9fe6-0c0e6c3a378e.PNG)

Pero todo el resto espectacular !!!

**Comment by havikhavik** [comment]
Hola Matías, gracias por mirar y probar mi Portfolio! 

En cuanto a los problemas de layout que mencionas, 1) Implementando la propiedad background-size: cover; en el .hero-section la imagen ahora ocupa todo el ancho de pantalla 2) ocurría porque el ultimo elemento rompía el ancho en pantalla, lo pude solucionar implementando la propiedad grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));  Lo que hace esta propiedad es definir de forma automática la cantidad de columnas dependiendo el tamaño de la pantalla. 

Gracias por chequear el trabajo y subo capturas con el diseño funcionando correctamente!

![fixed](https://user-images.githubusercontent.com/74418375/137241537-fe452a91-4ff9-4f16-b579-961d93eb4345.jpg)
![fixed3](https://user-images.githubusercontent.com/74418375/137241534-b559c5d3-6154-4064-9dae-40b5cb12f880.jpg)
![fixed2](https://user-images.githubusercontent.com/74418375/137241540-a965d9f3-d392-495f-9ec3-68460eb8feec.jpg)
![fixed4](https://user-images.githubusercontent.com/74418375/137242834-1049610b-a1de-40fe-9169-c7240ccc459f.jpg)
