### ISSUE TITLE
Review #3 - Pequeño detalle hero-section.

### ISSUE THREAD

**Issue by FacundoEG** [havikhavik/apx-desafio-m4#3]
Hola Havik! primero que todo te felicito por finalizar el desafío del modulo 4! 

Mira probé todas las pages y el form, anduvo todo muy bien! así que buenísimo por eso.

Solo te quiero sugerir una cosita muy mínima, fíjate que el fondo de la hero-section en modo mobile se "repite" y como que se corta:

![image](https://user-images.githubusercontent.com/79592789/137231290-dd846396-b7b5-42a2-943d-a63fce13322b.png)

Te puedo sugerir que pruebes una propiedad llamada "background-size" que te permite manipular que sucede con el tamaño del fondo en si:

![image](https://user-images.githubusercontent.com/79592789/137231461-3e14208d-cace-449e-868b-ceb1a7e7c5f3.png)

Es algo muy chiquito y mas que nada un detalle, por lo demás quedo todo muy lindo! así que LGTM!

Abrazo y suerte para el próximo modulo!

**Comment by havikhavik** [comment]
Hola Facundo, gracias por mirar y probar mi Portfolio! 

En cuanto al inconveniente que mencionas, implementando la propiedad background-size: cover; en el .hero-section la imagen ahora ocupa todo el ancho de pantalla.

Gracias por chequear el trabajo y traer la sugerencia al problema, subo captura con el diseño funcionando correctamente!

![fixed4](https://user-images.githubusercontent.com/74418375/137242834-1049610b-a1de-40fe-9169-c7240ccc459f.jpg)

**Comment by FacundoEG** [comment]
Genial Lucas! me alegro que hayas tomado la sugerencia! 

Te dejo un abrazo y suerte en el proximo modulo!
